language: node_js
node_js:
  - "10"
  - "8"
  - "6"
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
  - yarn run lint
  - yarn test --coverage
after_script: greenkeeper-lockfile-upload
after_success:
  - bash <(curl -s https://codecov.io/bash)
